<?php
/**
 * CheckoutFormFulfillmentStatus
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  Phobetor\Allegro
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Allegro REST API
 *
 * https://developer.allegro.pl/about  Documentation is generated from [this](https://developer.allegro.pl/swagger.yaml) OpenAPI 3.0 specification file.
 *
 * The version of the OpenAPI document: latest
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Phobetor\Allegro\Model;
use \Phobetor\Allegro\ObjectSerializer;

/**
 * CheckoutFormFulfillmentStatus Class Doc Comment
 *
 * @category Class
 * @description Order seller status.
 * @package  Phobetor\Allegro
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CheckoutFormFulfillmentStatus
{
    /**
     * Possible values of this enum
     */
    const _NEW = 'NEW';
    const PROCESSING = 'PROCESSING';
    const READY_FOR_SHIPMENT = 'READY_FOR_SHIPMENT';
    const SENT = 'SENT';
    const CANCELLED = 'CANCELLED';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::_NEW,
            self::PROCESSING,
            self::READY_FOR_SHIPMENT,
            self::SENT,
            self::CANCELLED,
        ];
    }
}


