<?php
/**
 * SellerOfferStatsResponseDtoTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Phobetor\Allegro
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Allegro REST API
 *
 * https://developer.allegro.pl/about  Documentation is generated from [this](https://developer.allegro.pl/swagger.yaml) OpenAPI 3.0 specification file.
 *
 * The version of the OpenAPI document: latest
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Phobetor\Allegro\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * SellerOfferStatsResponseDtoTest Class Doc Comment
 *
 * @category    Class
 * @description Data class for a specific seller events. Includes a list of OfferStatResponseDto grouped by date and a list of ClassifiedEventStat grouped by EventType for a specific period.
 * @package     Phobetor\Allegro
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class SellerOfferStatsResponseDtoTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "SellerOfferStatsResponseDto"
     */
    public function testSellerOfferStatsResponseDto()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "event_stats_total"
     */
    public function testPropertyEventStatsTotal()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "events_per_day"
     */
    public function testPropertyEventsPerDay()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
