<?php
/**
 * BadgeCampaignsApiTest
 * PHP version 7.2
 *
 * @category Class
 * @package  Phobetor\Allegro
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Allegro REST API
 *
 * https://developer.allegro.pl/about  Documentation is generated from [this](https://developer.allegro.pl/swagger.yaml) OpenAPI 3.0 specification file.
 *
 * The version of the OpenAPI document: latest
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Phobetor\Allegro\Test\Api;

use \Phobetor\Allegro\Configuration;
use \Phobetor\Allegro\ApiException;
use \Phobetor\Allegro\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * BadgeCampaignsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Phobetor\Allegro
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class BadgeCampaignsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for badgeApplicationsGetAll
     *
     * [BETA] Get a list of badge applications.
     *
     */
    public function testBadgeApplicationsGetAll()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for badgeApplicationsGetOne
     *
     * [BETA] Get a badge application details.
     *
     */
    public function testBadgeApplicationsGetOne()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for badgeCampaignsGetAll
     *
     * [BETA] Get a list of available badge campaigns.
     *
     */
    public function testBadgeCampaignsGetAll()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getBadges
     *
     * [BETA] Get a list of badges.
     *
     */
    public function testGetBadges()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postBadges
     *
     * [BETA] Apply for badge in selected offer.
     *
     */
    public function testPostBadges()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
